### ISSUE TITLE
API is crashing on production & staging in cloud.gov

### ISSUE THREAD

**Issue by okamanda** [presidential-innovation-fellows/code-gov-api#37]
I've just tried pushing both the production version and the staging version of code-api (and code-api-staging), and gotten the following error messages:

<img width="1280" alt="screen shot 2017-07-18 at 2 08 23 pm" src="https://user-images.githubusercontent.com/6461538/28332725-ca1d10f4-6bc3-11e7-8876-a9939387037a.png">

<img width="1280" alt="screen shot 2017-07-18 at 2 16 19 pm" src="https://user-images.githubusercontent.com/6461538/28332723-ca18cc24-6bc3-11e7-8284-2f98428f4e4c.png">

It looks like 'request-promise' module is being called but it isn't found. But I don't seem to have a problem running the API when I load it locally.

@valedaemon Any ideas?

**Comment by PhilipBale** [comment]
run npm i 'request-promise' --save

The module is install locally but not in the package manager

**Comment by okamanda** [comment]
thanks @PhilipBale 

running `npm i 'request-promise' --save` and `npm i 'sleep' --save` worked!
