### ISSUE TITLE
null license produces warning on dashboard

### ISSUE THREAD

**Issue by jfredrickson5** [presidential-innovation-fellows/code-gov-api#9]
Schema 1.0.1 specifies that the `license` field can be null or a string. If it is null, the dashboard outputs a warning:

```
{
  "keyword": "type",
  "dataPath": ".license",
  "schemaPath": "#/properties/license/type",
  "params": {
    "type": "string"
  },
  "message": "should be string"
}
```

The dashboard should not output a warning if the `license` field is null, since the schema allows it.

**Comment by okamanda** [comment]
This should be resolved in the latest version of the compliance dashboard
